### ISSUE TITLE
xpro aka tweetdeck not working more after 1.7.5.1, with last version too

### ISSUE THREAD

**Issue by speedyscns** [dimdenGD/OldTwitter#414]
**Describe the bug**
After v1.7.5.1 update and also with last v1.7.5.3 script error with XPro aka tweetdeck, unable to load page, it works disabling addon only

**Screenshots**
image here --> https://ibb.co/WVQT0j7

**Browser**
tested with librewolf-116.0.1 and librewolf-116.0.2-1 (last version)

**Links**
https://tweetdeck.twitter.com/ (it works if addon is disabled)

**OldTwitter version**
v1.7.5.3

**Comment by dimdenGD** [comment]
Fixed

**Comment by PRGilland** [comment]
It's still broken for me on 1.7.5.4. All Twitter-related addons disabled excluding OldTwitter.

**Comment by dimdenGD** [comment]
Try restarting your browser, if this doesn't solve it, open devtools with F12 and go to Network tab and refresh page and show what errors it shows

**Comment by PRGilland** [comment]
Closing firefox does not seem to fix it. Upon activating OldTwitter while Tweetdeck is open, the Transferred tab drops a constant string of CORS No Allow Credentials and NS_ERROR_DOM_BAD_URI from the domain of api.twitter.com, none of which are present when your addon is disabled.

**Comment by dimdenGD** [comment]
Released 1.7.5.5, check if it fixes now

**Comment by PRGilland** [comment]
I think that did the trick, thank you. I'll let you know if I come across any more issues
