### ISSUE TITLE
White blank page when using Kiwi Browser (v1.8.3.5) (4/1/24)

### ISSUE THREAD

**Issue by klmplix** [dimdenGD/OldTwitter#727]
When trying to view on my mobile device through Kiwi, it keeps giving me a white blank page despite the refreshes and restarts. I tried to clear cache, force stop, even clear data but nothing seems to fix the issue. It works fine on desktop but nothing seems to work on mobile.

**Browser**
Kiwi Browser 

**Version**
v1.8.3.5

**Comment by JabbingQuirker** [comment]
I am also getting this error on chrome.

**Comment by BlindWanda** [comment]
I was getting a blank page too in Chrome, The way I fixed it was by copying the old "script folder" over the top of the new one, which seems to have fixed it for now.

**Comment by Charsy89** [comment]
I'm getting this too, using LibreWolf. I updated from version 1.8.1.3, IIRC.
It still occurs on the latest commit as of writing (6410db69).
I've attached some console output.
![2024-04-02-182549_1911x380_scrot](https://github.com/dimdenGD/OldTwitter/assets/28523197/65995276-8c3b-4940-8caf-489b05bcb299)

**Comment by samiscoolest** [comment]
im experiencing this now on desktop vivaldi

**Comment by Charsy89** [comment]
This is resolved for me as of version 1.8.3.7.
