### ISSUE TITLE
Twitter API failing Verify Credentials - Page does not exist

### ISSUE THREAD

**Issue by AlexDeveloperUwU** [dimdenGD/OldTwitter#967]
**Describe the bug**
The website just freezes with the plugin enabled, as the https://api.x.com/1.1/account/verify_credentials.json returns error 404, making some parts of the website non-functional or freezing in the loading.

I also tried log out log in but it also does not work. Also tried in another pc, but same result. Quite an strange behavior.

**Screenshots**
![image](https://github.com/user-attachments/assets/9f240660-2666-4cd9-a390-479ac68ebbdf)
![image](https://github.com/user-attachments/assets/c17da199-92db-4025-8dea-02cccbbc7691)
![image](https://github.com/user-attachments/assets/0dbb771f-488e-4885-bb12-5b5d518ed386)

**Browser**
Chromium 131.0.6778.70, also tested in Chrome 131.0.6778.70 (yeah, same version).

**Links**
Every page of X

**OldTwitter version**
v1.8.9

**Comment by 2lipp2p** [comment]
i have the same problem on firefox 115.15, only feed works cant go to dropdown menu, profile, notifs, or any other page

**Comment by samiscoolest** [comment]
also experiencing

**Comment by dwnas** [comment]
also experiencing on firefox nightly 134.0a1 (2024-11-16)

**Comment by dimdenGD** [comment]
Fixed

**Comment by 2lipp2p** [comment]
> Fixed

still getting this post update, is it firefox version? 

There was an error in initializing security header generator: Error: Failed to fetch homepage: TypeError: https:/// is not a valid URL.
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0
OldTwitter doesn't allow unsigned requests anymore for your account security. Currently the main reason for this happening is social network tracker protection blocking the script. Try disabling such settings in your browser and extensions that do that and refresh the page. This can also happen if you're not logged in.
